### ISSUE TITLE
Neutral data check

### ISSUE THREAD

**Issue by douglasjacobsen** [UoB-HPC/performance-portability#1]
On this data set: https://github.com/UoB-HPC/performance-portability/blob/master/metrics/data/neutral.csv

The Naples data line reads `X27.0` for OpenACC.

**Comment by tomdeakin** [comment]
Removed in 34e52a00000747af30843a11519f684385a5aaba

From the P3HPC paper which is the source of the data:
> Note that the OpenACC and OpenCL versions are missing the AoS implementation at this time, and so we omit the CPU results.
