### ISSUE TITLE
Synthetic data update

### ISSUE THREAD

**Issue by douglasjacobsen** [UoB-HPC/performance-portability#2]
In this data file: https://github.com/UoB-HPC/performance-portability/blob/master/metrics/data/synthetic.csv

We want to update the 0 data points in the existing data for bimodel to something small (like 5 or 10)

Also, we want to add a new "application" named "Not performance portable" that mimics "Not portable" with the 0 data points being replaced with small values as well.

**Comment by tomdeakin** [comment]
> We want to update the 0 data points in the existing data for bimodel to something small (like 5 or 10)

Fixed by 862c588

> Also, we want to add a new "application" named "Not performance portable" that mimics "Not portable" with the 0 data points being replaced with small values as well.

See 9424a8e
