### ISSUE TITLE
2020 migration progress

### ISSUE THREAD

**Issue by tom91136** [UoB-HPC/performance-portability#3]
Tested targets are ticked off to track progress:

 - [ ] babelstream
   - [ ] ampere-zoo
   - [ ] fetch.sh
   - [ ] gtx2080ti-zoo
   - [ ] k20-bcp3
   - [ ] k20x-swan
   - [ ] knl-swan
   - [ ] naples-oracle
   - [ ] p100-isambard
   - [ ] power9-isambard
   - [ ] radeonvii-zoo
   - [ ] skl-swan
   - [ ] tx2-isambard
   - [ ] v100-bluegem
   - [ ] v100-isambard
 - [ ] cloverleaf
   - [ ] ampere-zoo
   - [ ] aurora-zoo
   - [ ] bdw-swan
   - [ ] fetch.sh
   - [ ] gtx2080ti-zoo
   - [ ] k20-bcp3
   - [ ] knl-swan
   - [ ] naples-oracle
   - [ ] p100-isambard
   - [ ] power9-isambard
   - [ ] radeonvii-zoo
   - [ ] skl-horizon
   - [ ] skl-swan
   - [ ] tx2-foxconn
   - [ ] tx2-isambard
   - [ ] v100-bluegem
   - [ ] v100-isambard
 - [ ] neutral
   - [ ] ampere-zoo
   - [ ] bdw-swan
   - [ ] fetch.sh
   - [ ] fetch_kokkos.sh
   - [ ] fetch_ocl.sh
   - [ ] gtx2080ti-zoo
   - [ ] k20-bcp3
   - [ ] naples-oracle
   - [ ] p100-isambard
   - [ ] power9-isambard
   - [ ] radeonvii-zoo
   - [ ] skl-horizon
   - [ ] skl-swan
   - [ ] tx2-foxconn
   - [ ] tx2-isambard
   - [ ] v100-isambard
 - [ ] minifmm
   - [ ] ampere-zoo
   - [ ] fetch.sh
   - [ ] gtx2080ti-zoo
   - [ ] k20-bcp3
   - [ ] knl-swan
   - [ ] naples-oracle
   - [ ] p100-isambard
   - [ ] power9-isambard
   - [ ] skl-swan
   - [ ] v100-isambard
 - [ ] tealeaf
   - [ ] ampere-zoo
   - [ ] aurora-zoo
   - [ ] bdw-swan
   - [ ] fetch.sh
   - [ ] gtx2080ti-zoo
   - [ ] k20-bcp3
   - [ ] knl-swan
   - [ ] naples-oracle
   - [ ] p100-isambard
   - [ ] power9-isambard
   - [ ] skl-horizon
   - [ ] skl-swan
   - [ ] tx2-foxconn
   - [ ] tx2-isambard
   - [ ] v100-isambard

**Comment by tomdeakin** [comment]
Good idea! The platform and application list is different to this though, so perhaps double check against the list in Slack.
